pipeline {
    agent any

    stages {
        stage('Run Newman tests and generate Allure report') {
            steps {
                bat 'scripts\\run-tests.bat'
            }
        }

        stage('Run k6 performance test on server') {
            steps {
                bat 'scripts\\run-k6-tests.bat'
            }
        }
    }
}
