pipeline {
    agent any

    stages {
        stage('Run Newman tests and generate Allure report') {
            steps {
                bat 'scripts\\run-tests.bat'
            }
        }

        stage('Run k6 performance test on server') {
            steps {
                bat 'k6 run k6_tests\\test-post-server.js'
            }
        }

        stage('Publish Allure report to GitHub Pages') {
            steps {
                bat '''
                cd ..\\qa-allure-reports
                git add .
                git commit -m "Update Allure report"
                git push origin main
                '''
            }
        }
    }
}