pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/OlgaVashurina/k6-performance-tests.git'
            }
        }

        stage('Install k6') {
            steps {
                sh 'which k6 || sudo apt install -y k6'
            }
        }

        stage('Run Local Tests') {
            steps {
                sh 'k6 run k6_tests/local/test-get-local.js'
                sh 'k6 run k6_tests/local/test-post-local.js'
                sh 'k6 run k6_tests/local/test-put-local.js'
                sh 'k6 run k6_tests/local/test-delete-local.js'
            }
        }

        stage('Run Server Tests') {
            steps {
                sh 'k6 run k6_tests/server/test_get.js'
                sh 'k6 run k6_tests/server/test-post-users.js'
            }
        }

        stage('Archive results') {
            steps {
                archiveArtifacts artifacts: 'results/*', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}