jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Allure Commandline
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
          unzip allure.zip -d $HOME/allure
          echo "$HOME/allure/bin" >> $GITHUB_PATH

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean